services:
  - type: web
    name: sekai-snake
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: sekai-snake
          envVarKey: PORT
      - key: DATA_DIR
        value: /var/data
    autoDeploy: true
    branch: main
    disk:
      name: sekai-snake-data
      mountPath: /var/data
      sizeGB: 1
